### ISSUE TITLE
Use conda-forge dependencies instead of vendoring

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/blosc-feedstock#18]
Currently we are using `blosc`'s internally vendored dependencies instead of our own. We can fix that though we need to set [some flags]( https://github.com/Blosc/c-blosc/blob/v1.14.0/CMakeLists.txt#L24-L35 ) for the build to switch. Also will need to evaluate what dependencies actually support all platforms and both Windows runtimes.

**Comment by marscher** [comment]
does this also account for the fact, that this blosc build does not contain compressor algorithms like lz4, zlib etc.?

**Comment by marscher** [comment]
my statement is not true.

**Comment by hmaarrfk** [comment]
I did this in:
https://github.com/conda-forge/c-blosc2-feedstock/pull/18
