### ISSUE TITLE
No 1.14.0 win-64 packages

### ISSUE THREAD

**Issue by tomkooij** [conda-forge/blosc-feedstock#22]
Although the Appveyor [build passed](https://ci.appveyor.com/project/conda-forge/blosc-feedstock/branch/master) and packages are uploaded, there are [no blosc packages in the current win-64 conda-forge channel](https://anaconda.org/conda-forge/blosc).

This breaks the latest conda-forge pytables as this is now built against the 1.14.x package from the `anaconda` channel. (That is not available by default on my machine)

I will make a PR to build the current version (1.14.3), this will probably (maybe?) fix this.

**Comment by tomkooij** [comment]
I just noticed #20 ... My bad. Sorry about this. I'll close this, to continue in #20

**Comment by jakirkham** [comment]
Please see issue ( https://github.com/conda-forge/blosc-feedstock/issues/19 ). PRs welcome (including ones duplicating and/or amending my own). :)
