### ISSUE TITLE
static library files should be removed

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/blosc-feedstock#54]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

It seems that the `.a` files are being built and installed. We should remove them as per conda-forge policy. If users require them, I think we can reintroduce them through a split package.

### Installed packages

```shell
OSX: blosc-1.21.1-h6b673d3_1
```

### Environment info

```shell
OSX: blosc-1.21.1-h6b673d3_1
```

**Comment by jakirkham** [comment]
Submitted PR ( https://github.com/conda-forge/blosc-feedstock/pull/56 )
